name: License Compliance Verification

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  license-compliance:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      # Cache Gradle dependencies to speed up the build
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Install dependencies and build project
      - name: Build with Gradle
        run: ./gradlew build

      # Generate License Report (using Gradle License plugin)
      - name: Generate License Report
        run: ./gradlew generateLicenseReport

      # Create the License Report XML
      - name: Create License Finder Report XML
        run: |
            echo "Creating License Compliance Report"
            LICENSE_HTML="build/reports/dependency-license/index.html"
            
            # Start XML generation
            echo '<?xml version="1.0" encoding="UTF-8"?>' > license_finder_report.xml
            echo '<testsuites>' >> license_finder_report.xml
            echo '<testsuite name="License Compliance" tests="0">' >> license_finder_report.xml  # Default tests count as 0

            # Check if the HTML report exists
            if [ -f "$LICENSE_HTML" ]; then
              # Extract the count of dependencies (assuming each <tr> contains a module's information)
              DEPENDENCIES_COUNT=$(grep -oP '<tr><td>\K[^<]+' "$LICENSE_HTML" | wc -l)

              # Check if dependencies are found
              if [ "$DEPENDENCIES_COUNT" -gt 0 ]; then
                # Update the tests count in the XML report
                echo "  <testsuite name=\"License Compliance\" tests=\"$DEPENDENCIES_COUNT\">" >> license_finder_report.xml

                # Loop through each module and extract the module name and license information
                grep -oP '<tr><td>\K[^<]+' "$LICENSE_HTML" | while read -r moduleName; do
                  # Extract license info related to the module
                  license=$(grep -A 1 "$moduleName" "$LICENSE_HTML" | tail -n 1)

                  # Add the information to the XML file
                  echo "  <testcase name=\"License Check - $moduleName\" classname=\"License Compliance\">" >> license_finder_report.xml
                  echo "    <system-out>Module: $moduleName\\nLicense: $license</system-out>" >> license_finder_report.xml
                  echo "  </testcase>" >> license_finder_report.xml
                done
              else
                echo "No dependencies found in the HTML report"  # Log a message if no dependencies are found
              fi
            else
              # If the HTML file doesn't exist, log the error and exit
              echo "Error: License report HTML file not found at $LICENSE_HTML"
              find build -type f -name "*.html"  # List all HTML files in the build directory for troubleshooting
              exit 1
            fi

            # Close the XML tags
            echo '</testsuite>' >> license_finder_report.xml
            echo '</testsuites>' >> license_finder_report.xml

            # Log completion
            echo "License report has been generated as license_finder_report.xml"

      # Publish the generated XML license compliance report
      - name: Publish License Compliance Results
        uses: EnricoMi/publish-unit-test-result-action@v2.2.0
        with:
          files: license_finder_report.xml
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Upload the generated XML as an artifact (optional, for future reference)
      - name: Upload License Report Artifact
        uses: actions/upload-artifact@v3
        with:
          name: license-compliance-report
          path: license_finder_report.xml
